# repos:
#   - repo: https://github.com/thoughtworks/talisman
#     rev: v1.16.0  # You can check the latest release on GitHub
#     hooks:
#       - id: talisman
#         name: Talisman - Detect Secrets
#         description: Detect secrets and sensitive information
#         language: system  # Talisman is not a Python-based hook
#         types: [text]
repos:
  -   repo: https://github.com/thoughtworks/talisman
      rev: 'v1.32.2'  # Update me!
      hooks:
        # both pre-commit and pre-push supported
        # -   id: talisman-push
        - id: talisman-commit
          # name: Talisman - Detect Secrets
          # description: Detect secrets and sensitive information
          # language: system
          # exclude: ^\.env$
          

# .pre-commit-config.yaml
# repos:
#   - repo: https://github.com/thoughtworks/talisman
#     rev: v3.2.0  # Use the version you want or the latest
#     hooks:
#       - id: talisman
#         name: Talisman - Detect Secrets
#         description: Detect secrets and sensitive information
#         language: system
#         types: [text]
