name: SecurityPipeline

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  secret-scan:
    name: Horusec scan
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Gitleaks Docker image with custom rules
        run: |
          docker build -t gitleaks-custom -f ./Dockerfile .

      # - name: Run Gitleaks with custom rules
      #   run: |
      #     docker run --rm \
      #       -v ${{ github.workspace }}:/app \
      #       -w /app \
      #       gitleaks-custom detect \
      #         --source=/app \
      #         --config=/rules/rules.toml \
      #         --no-git \
      #         --verbose \
      #         --exit-code 1
      - name: Run Gitleaks with custom rules
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            gitleaks-custom detect \
              --source=/app \
              --config=/app/services/formatters/leaks/deployments/rules.toml \
              --no-git \
              --verbose \
              --exit-code 1

