name: SecurityPipeline

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  secret-scan:
    uses: PoorneshORG/SecretScan/.github/workflows/secretscan.yml@main
    with:
      fetch-depth: 0 # Optional: pass any input if needed in reusable workflow
