name: SecurityPipeline

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  secret-scan:
    name: Gitleaks-proxy
    uses: ./.github/workflows/secret-scan.yml
